name: Visit Site Daily

on:
  schedule:
    - cron: "*/15 * * * *"  # Toutes les quarts d'heure
  workflow_dispatch:     # Permet de lancer manuellement si besoin

jobs:
  visit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd cron
        npm install

    - name: Install Playwright browsers
      run: |
        cd cron
        npx playwright install

    - name: Run Playwright script
      run: |
        cd cron
        npm run visit
